function freezeMetadata(items) {
  return Object.freeze(items.map(item => Object.freeze({
    ...item,
    profiles: Object.freeze([...item.profiles]),
  })));
}

export const ruleMetadata = freezeMetadata([
  {
    id: 'nihongo-slopless/hidden-unicode-controls',
    category: 'surface-readability',
    severity: 'error',
    goal: 'ゼロ幅文字や双方向制御文字など、読み手に見えない制御文字の混入を検出する',
    notGoal: 'Unicode文字や多言語テキストの利用そのものを否定することではない',
    fixHint: '意図的な制御文字でなければ削除し、コピー元や生成元で混入した箇所を確認する',
    profiles: ['minimal', 'general', 'business', 'technical', 'research', 'public', 'web', 'agent-output', 'strict'],
  },
  {
    id: 'nihongo-slopless/placeholder',
    category: 'agent-artifacts',
    severity: 'error',
    goal: 'TODO、仮置き、伏せ字、未記入欄など、提出前に処理すべき未完成の痕跡を検出する',
    notGoal: '作業中の下書きやテンプレートで意図的に残した目印を禁止することではない',
    fixHint: '具体名、日付、値、出典を埋めるか、公開文書に不要な目印を削除する',
    profiles: ['minimal', 'general', 'business', 'technical', 'research', 'public', 'web', 'agent-output', 'strict'],
  },
  {
    id: 'nihongo-slopless/chat-response-leakage',
    category: 'agent-artifacts',
    severity: 'warning',
    goal: '独立文書に残ると役割が弱いチャット応答の前置きや締めを検出する',
    notGoal: '対話ログ、FAQ、チャット形式の教材で必要な発話表現を削らせることではない',
    fixHint: '本文に必要な情報だけを残し、対話上の挨拶、前置き、依頼待ち表現を削る',
    profiles: ['minimal', 'general', 'business', 'technical', 'research', 'public', 'web', 'agent-output', 'strict'],
  },
  {
    id: 'nihongo-slopless/list-intro-padding',
    category: 'style-drift',
    severity: 'info',
    goal: '情報量の少ないリスト導入や説明前置きが本文を薄めている箇所を検出する',
    notGoal: '読み手の案内として必要な導入文や、授業資料の段階的な説明を否定することではない',
    fixHint: '見出しや箇条書きで構造が伝わる場合は、前置きを削って要点から始める',
    profiles: ['general', 'business', 'technical', 'public', 'web', 'agent-output', 'strict'],
  },
  {
    id: 'nihongo-slopless/long-sentence',
    category: 'surface-readability',
    severity: 'warning',
    goal: '一文に複数の論点が詰まり、読み手が追いにくい長文を検出する',
    notGoal: '法令文、引用文、専門的な定義文など、意図的に長くなる文を一律に短くすることではない',
    fixHint: '主張、根拠、条件、例を分け、1文1論点に近づける',
    profiles: ['minimal', 'general', 'business', 'technical', 'research', 'public', 'web', 'agent-output', 'strict'],
  },
  {
    id: 'nihongo-slopless/long-paragraph',
    category: 'surface-readability',
    severity: 'warning',
    goal: '段落が長すぎる、または文数が多すぎて役割が見えにくい箇所を検出する',
    notGoal: '引用、逐語記録、意図的な長段落の文体を機械的に分割させることではない',
    fixHint: '段落の役割を一つに絞り、主張、根拠、例、含意を段落単位で分ける',
    profiles: ['minimal', 'general', 'business', 'technical', 'research', 'public', 'web', 'agent-output', 'strict'],
  },
  {
    id: 'nihongo-slopless/empty-conclusion',
    category: 'style-drift',
    severity: 'warning',
    goal: '結論に見えるが、成果、対象、条件、次の確認事項が本文から読み取りにくい締めを検出する',
    notGoal: '余韻を持たせる文学的な結びや、文脈上十分に具体化された総括を否定することではない',
    fixHint: '何が分かったか、誰に関係するか、どの条件で言えるか、次に何を確認するかを補えるか確認する',
    profiles: ['general', 'business', 'research', 'public', 'web', 'agent-output', 'strict'],
  },
  {
    id: 'nihongo-slopless/weasel-phrases',
    category: 'evidence-responsibility',
    severity: 'warning',
    goal: '主体、根拠、範囲を確認したい表現が重なっている箇所を検出する',
    notGoal: '不確実性を丁寧に扱うための限定表現そのものを禁止することではない',
    fixHint: '誰が述べたのか、どのデータに基づくのか、対象範囲や例外条件を本文で補えるか確認する',
    profiles: ['general', 'business', 'research', 'public', 'web', 'agent-output', 'strict'],
  },
  {
    id: 'nihongo-slopless/citation-needed',
    category: 'evidence-responsibility',
    severity: 'warning',
    goal: '時事性、実証性、新規性を含む主張に根拠表示が不足している可能性を検出する',
    notGoal: '常識的な説明や本文の別箇所で根拠済みの記述に、機械的な出典追加を強制することではない',
    fixHint: '出典、年、調査対象、URL、図表番号、観察条件などを添える',
    profiles: ['general', 'business', 'technical', 'research', 'public', 'web', 'agent-output', 'strict'],
  },
  {
    id: 'nihongo-slopless/absolute-claim',
    category: 'evidence-responsibility',
    severity: 'warning',
    goal: '適用範囲や例外条件が必要になりやすい強い断定表現を検出する',
    notGoal: '明確な根拠や定義がある断定、仕様上必要な禁止や必須条件を弱めることではない',
    fixHint: '対象範囲、例外条件、根拠、前提を示すか、断定の強さを調整する',
    profiles: ['general', 'business', 'technical', 'research', 'public', 'web', 'agent-output', 'strict'],
  },
  {
    id: 'nihongo-slopless/unscoped-generalization',
    category: 'evidence-responsibility',
    severity: 'warning',
    goal: '「あらゆる〜」「いかなる〜も」「どんな〜でも」「常に〜」のような集合全体への主張で、対象範囲や条件が文中に示されていない箇所を検出する',
    notGoal: '文学的、慣用的、定義的な総称表現や、対象範囲が文脈で明確な記述を否定することではない',
    fixHint: '対象範囲(時点、領域、対象者、条件)を本文で補えるか、断定の強さを調整できるか確認する',
    profiles: ['general', 'business', 'technical', 'research', 'public', 'web', 'agent-output', 'strict'],
  },
  {
    id: 'nihongo-slopless/no-numerics-claim',
    category: 'evidence-responsibility',
    severity: 'warning',
    goal: '「大幅に向上」「劇的に改善」など強度語と効果語の近接ペアに、数値・期間・対比・出典が見当たらない箇所を検出する',
    notGoal: '感想や導入文での強度語そのものを禁止することや、根拠が別段落で示されている文を機械的に指摘することではない',
    fixHint: '数値、期間、対比、出典のいずれかを補えるか、強度語の必要性を見直せるか確認する',
    profiles: ['general', 'business', 'technical', 'research', 'public', 'web', 'agent-output', 'strict'],
  },
  {
    id: 'nihongo-slopless/abstract-noun-stack',
    category: 'semantic-density',
    severity: 'warning',
    goal: '抽象語が密集し、対象や行動が見えにくい文を検出する',
    notGoal: '哲学的、文学的、理論的な抽象表現を否定することではない',
    fixHint: '対象、数値、事例、条件、行動のいずれかを補う',
    profiles: ['general', 'business', 'technical', 'research', 'public', 'web', 'agent-output', 'strict'],
  },
  {
    id: 'nihongo-slopless/nominalization-density',
    category: 'semantic-density',
    severity: 'warning',
    goal: '「性」「化」「的」などの名詞化や抽象化が重なり、動作や主体が見えにくい文を検出する',
    notGoal: '専門用語、学術用語、概念整理として必要な名詞表現を禁止することではない',
    fixHint: '名詞の鎖をほどき、誰が何をするのかを動詞中心に書き直す',
    profiles: ['general', 'business', 'technical', 'research', 'public', 'web', 'agent-output', 'strict'],
  },
  {
    id: 'nihongo-slopless/excessive-politeness',
    category: 'agency-action',
    severity: 'warning',
    goal: '丁寧表現や謙譲表現が重なり、主体、行動、依頼内容が読み取りにくい箇所を検出する',
    notGoal: '礼儀、敬語、組織文書として必要な丁寧さを否定することではない',
    fixHint: '敬語の必要性を保ちつつ、誰が何をするのか、何を依頼しているのかを補えるか確認する',
    profiles: ['general', 'business', 'public', 'web', 'agent-output', 'strict'],
  },
  {
    id: 'nihongo-slopless/actorless-action',
    category: 'agency-action',
    severity: 'warning',
    goal: '対応、検討、改善などの行動表現で、主体や期限が見えにくい文を検出する',
    notGoal: '組織文書で必要な検討表現や、前後の文脈で担当と期限が明確な記述を否定することではない',
    fixHint: '誰が、いつまでに、どの基準で対応するのかを補う',
    profiles: ['general', 'business', 'technical', 'research', 'public', 'web', 'agent-output', 'strict'],
  },
  {
    id: 'nihongo-slopless/deadline-missing',
    category: 'agency-action',
    severity: 'warning',
    goal: '対応・検討・推進などの行動述語で、期限や時点が文中に見えない箇所を検出する',
    notGoal: '随時運用や仕様上期限が不要な文、前後の文脈で期限が明確な記述を否定することではない',
    fixHint: 'いつまでに、何を完了するのかを補えるか、代替となるマイルストーンを示せるか確認する',
    profiles: ['general', 'business', 'technical', 'research', 'public', 'web', 'agent-output', 'strict'],
  },
  {
    id: 'nihongo-slopless/same-ending',
    category: 'surface-readability',
    severity: 'info',
    goal: '同じ文末が連続し、読みのリズムが固定されている箇所を検出する',
    notGoal: '論文調、仕様書、教材などで必要な文末統一を崩すことではない',
    fixHint: '意図せず同じリズムになっている箇所だけ、文の長短、述語、体言止めを調整する',
    profiles: ['general', 'public', 'web', 'agent-output', 'strict'],
  },
  {
    id: 'nihongo-slopless/repeated-connectors',
    category: 'surface-readability',
    severity: 'info',
    goal: '近い範囲で同じ文頭接続語が反復し、文章構造が単調になっている箇所を検出する',
    notGoal: '論理関係を明示するために必要な接続語を削らせることではない',
    fixHint: '接続語の反復で構造を支える代わりに、段落、見出し、文順で論理関係を示す',
    profiles: ['general', 'business', 'research', 'public', 'web', 'agent-output', 'strict'],
  },
  {
    id: 'nihongo-slopless/translationese',
    category: 'style-drift',
    severity: 'info',
    goal: '文が重くなりやすい言い回しを、編集確認の対象として検出する',
    notGoal: '法務、行政、学術文書で必要な厳密表現を一律に口語化することではない',
    fixHint: '短く言えるか、動詞を直接使えるか、読者に必要な精度かを確認する',
    profiles: ['general', 'business', 'technical', 'research', 'public', 'web', 'agent-output', 'strict'],
  },
  {
    id: 'nihongo-slopless/buzzword-density',
    category: 'semantic-density',
    severity: 'info',
    goal: 'バズワードや政策語が密集し、実践、対象、成果、評価指標が見えにくい段落を検出する',
    notGoal: '分野で共有された用語や政策用語を使うこと自体を否定することではない',
    fixHint: '具体的な実践、対象者、成果物、評価指標、検証方法を補う',
    profiles: ['general', 'business', 'research', 'public', 'web', 'agent-output', 'strict'],
  },
  {
    id: 'nihongo-slopless/thin-sentence',
    category: 'semantic-density',
    severity: 'warning',
    goal: '長さはあるが、具体的な対象、数値、根拠、行動が乏しい文を検出する',
    notGoal: '導入、要約、抽象度の高い理論説明を一律に詳細化させることではない',
    fixHint: '誰が、何を、どの条件で、どう変えるのか、または根拠や具体例を足す',
    profiles: ['general', 'business', 'research', 'public', 'web', 'agent-output', 'strict'],
  },
  {
    id: 'nihongo-slopless/excessive-parentheses',
    category: 'surface-readability',
    severity: 'info',
    goal: '括弧補足が密集し、本文の流れや情報の主従が見えにくい段落を検出する',
    notGoal: '注釈、略語展開、出典表記など、読者に必要な補足を削らせることではない',
    fixHint: '重要な補足は本文に昇格し、不要な補足は削り、出典や注は別形式で整理する',
    profiles: ['general', 'business', 'technical', 'research', 'public', 'web', 'agent-output', 'strict'],
  },
  {
    id: 'nihongo-slopless/headline-decoration',
    category: 'surface-readability',
    severity: 'info',
    goal: '見出しの装飾記号が本文情報より目立ち、媒体目的や読者に合うか確認したい箇所を検出する',
    notGoal: 'ブログ、教材、広報で意図的に使う視覚的な強調を禁止することではない',
    fixHint: '装飾記号に頼らず、見出し語、階層、本文構造で強調を示す',
    profiles: ['general', 'public', 'web', 'agent-output', 'strict'],
  },
  {
    id: 'nihongo-slopless/over-possibility',
    category: 'style-drift',
    severity: 'info',
    goal: '段落内で推測・可能性表現が反復累積し、何が確かで何が未確定かが読み取りにくい箇所を検出する',
    notGoal: '推測表現そのものを禁止することや、慎重な留保表現を一律に削らせることではない',
    fixHint: '段落全体で何が確からしく、何が未確定なのかを区別できるか確認する',
    profiles: ['general', 'business', 'technical', 'research', 'public', 'web', 'agent-output', 'strict'],
  },
  {
    id: 'nihongo-slopless/unclear-deictic',
    category: 'style-drift',
    severity: 'info',
    goal: '段落内で指示詞(これ、それ、この、その等)が多く反復し、参照先が読み手に伝わりにくい可能性がある箇所を検出する',
    notGoal: '個別の指示詞使用や、接続辞として機能する「そのため」等の固定表現を否定することではない',
    fixHint: '指示詞を具体的な名詞に置き換えるか、段落構造を再編して参照先を近づける',
    profiles: ['business', 'technical', 'public', 'web', 'agent-output', 'strict'],
  },
]);

export const ruleMetadataById = Object.freeze(Object.fromEntries(
  ruleMetadata.map(item => [item.id, item]),
));

export function getRuleMetadata(id) {
  return ruleMetadataById[id] ?? ruleMetadataById[`nihongo-slopless/${id}`];
}
